# Generated by Django 5.0 on 2023-12-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0004_remove_order_products_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
