# Generated by Django 5.0 on 2023-12-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0005_rename_products_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
