# Generated by Django 4.2.7 on 2023-12-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0006_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='referenceNumber',
        ),
    ]
